// ACPI Tables
FILE FREEFORM = 7E374E25-8E01-4FEE-87F2-390C23C606CD {   
  SECTION RAW = Silicon/Qualcomm/sm8250/AcpiTables/dbg2.aml
  SECTION RAW = Platform/Lenovo/sm8250/AcpiTables/j716f/DSDT.aml
  SECTION RAW = Silicon/Qualcomm/sm8250/AcpiTables/Madt.aml
  SECTION RAW = Silicon/Qualcomm/sm8250/AcpiTables/Facp.aml
  SECTION RAW = Silicon/Qualcomm/sm8250/AcpiTables/Gtdt.aml
  SECTION RAW = Silicon/Qualcomm/sm8250/AcpiTables/IORT.aml
  SECTION RAW = Silicon/Qualcomm/sm8250/AcpiTables/Pptt.aml
  SECTION UI = "AcpiTables"
}

