boot magic: ANDROID!
kernel_size: 12160323
kernel load address: 0x00008000
ramdisk size: 19015900
ramdisk load address: 0x01000000
second bootloader size: 0
second bootloader load address: 0x00f00000
kernel tags load address: 0x00000100
page size: 4096
os version: 9.0.0
os patch level: 2020-03
boot image header version: 1
product name: 
command line args: console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xA84000 androidboot.hardware=qcom androidboot.console=ttyMSM0 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 service_locator.enable=1 swiotlb=2048 androidboot.configfs=true firmware_class.path=/vendor/firmware_mnt/image loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 buildvariant=user printk.devkmsg=on
additional command line args: 
recovery dtbo size: 0
recovery dtbo offset: 0x0000000000000000
boot header size: 1648
