  INF  Platform/EFI_Binaries/Drivers/sm6225/TzDxe/ScmDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/TzDxe/TzDxeLA.inf

  INF  Platform/EFI_Binaries/Drivers/sm6225/FontDxe/FontDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/QcomWDogDxe/QcomWDogDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6225/ChipInfoDxe/ChipInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/GLinkDxe/GLinkDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/SmemDxe/SmemDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/ULogDxe/ULogDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/NpaDxe/NpaDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6225/DALSYSDxe/DALSYSDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/VcsDxe/VcsDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/ClockDxe/ClockDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6225/HALIOMMUDxe/HALIOMMUDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/HWIODxe/HWIODxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/GpiDxe/GpiDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/I2CDxe/I2CDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/SPMIDxe/SPMIDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/SdccDxe/SdccDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/UFSDxe/UFSDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/TLMMDxe/TLMMDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6225/PlatformInfoDxe/PlatformInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/PmicDxe/PmicDxeLa.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/ChargerExDxe/ChargerExDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/QcomChargerDxe/QcomChargerDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/AdcDxe/AdcDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/TsensDxe/TsensDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/DDRInfoDxe/DDRInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6225/UsbMsdDxe/UsbMsdDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/UsbDeviceDxe/UsbDeviceDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/UsbConfigDxe/UsbConfigDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6225/PILDxe/PILDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/ShmBridgeDxe/ShmBridgeDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6225/ResetRuntimeDxe/ResetRuntimeDxe.inf