// sort alphabetically
  FILE DRIVER = 5bd181db-0487-4f1a-ae73-820e165611b3 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/ButtonsDxe/ButtonsDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ButtonsDxe/ButtonsDxe.efi
    SECTION UI = "ButtonsDxe"
  }

  FILE DRIVER = 10e193df-9966-44e7-b17c-59dd831e20fc {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/ChipInfo/ChipInfo.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ChipInfo/ChipInfo.efi
    SECTION UI = "ChipInfo"
  }

  FILE DRIVER = 4DB5DEA6-5302-4D1A-8A82-677A683B0D29 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/ClockDxe/ClockDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ClockDxe/ClockDxe.efi
    SECTION UI = "ClockDxe"
  }

  FILE DRIVER = ABA01FF8-2CCB-4E12-8B2E-CD3F4A742993 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/CmdDbDxe/CmdDbDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/CmdDbDxe/CmdDbDxe.efi
    SECTION UI = "CmdDbDxe"
  }

  FILE DRIVER = 8E9BD160-B184-11DF-94E2-0800200C9A66 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/DALSys/DALSys.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/DALSys/DALSys.efi
    SECTION UI = "DALSys"
  }

  FILE DRIVER = 8681cc5a-0df6-441e-b4b8-e915c538f067 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/DALTLMM/DALTLMM.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/DALTLMM/DALTLMM.efi
    SECTION UI = "DALTLMM"
  }

  FILE DRIVER = 7DB0793A-4402-4BE1-906E-D0FABAD2707E {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/DDRInfoDxe/DDRInfoDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/DDRInfoDxe/DDRInfoDxe.efi
    SECTION UI = "DDRInfoDxe"
  }

  FILE DRIVER = 9A00771F-36D4-4DD5-8916-C48ED9B16B86 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/HALIOMMU/HALIOMMU.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/HALIOMMU/HALIOMMU.efi
    SECTION UI = "HALIOMMU"
  }

  FILE DRIVER = af9763a2-033b-4109-8e17-56a98d380c92 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/HWIODxeDriver/HWIODxeDriver.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/HWIODxeDriver/HWIODxeDriver.efi
    SECTION UI = "HWIODxeDriver"
  }

  FILE DRIVER = 5824f9de-17d2-4b1f-a5fe-5eb77fa53093 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/ICBDxe/ICBDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ICBDxe/ICBDxe.efi
    SECTION UI = "ICBDxe"
  }

  FILE DRIVER = 04DE8591-D2B3-4077-BBBE-B12070094EB6 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/I2C/I2C.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/I2C/I2C.efi
    SECTION UI = "I2C"
  }

  FILE DRIVER = CB29F4D1-7F37-4692-A416-93E82E219711 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/NpaDxe/NpaDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/NpaDxe/NpaDxe.efi
    SECTION UI = "NpaDxe"
  }

  # FILE DRIVER = B43C22DB-6333-490C-872D-0A73439059FD {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/PdcDxe/PdcDxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/PdcDxe/PdcDxe.efi
  #   SECTION UI = "PdcDxe"
  # }

  FILE DRIVER = B105211B-BBBD-4ADD-A3B0-D1CF4A52154C {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/PlatformInfoDxeDriver/PlatformInfoDxeDriver.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/PlatformInfoDxeDriver/PlatformInfoDxeDriver.efi
    SECTION UI = "PlatformInfoDxeDriver"
  }

  FILE DRIVER = 5776232e-082d-4b75-9a0e-fe1d13f7a5d9 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/PmicDxe/PmicDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/PmicDxe/PmicDxe.efi
    SECTION UI = "PmicDxe"
  }

  FILE DRIVER = 0401b830-bff9-44a2-a5f6-95734a33c017 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/PwrUtilsDxe/PwrUtilsDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/PwrUtilsDxe/PwrUtilsDxe.efi
    SECTION UI = "PwrUtilsDxe"
  }

  # FILE DRIVER = 040e1e61-0afb-411b-9ec9-00f3fc59cc13 {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/QcomWDogDxe/QcomWDogDxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/QcomWDogDxe/QcomWDogDxe.efi
  #   SECTION UI = "QcomWDogDxe"
  # }

  FILE DRIVER = 3ae17db7-3cc5-4b89-9304-9549211057ef {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/ResetRuntimeDxe/ResetRuntimeDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ResetRuntimeDxe/ResetRuntimeDxe.efi
    SECTION UI = "ResetRuntimeDxe"
  }

  FILE DRIVER = CB29F4D1-7F37-4692-A416-93E82E219766 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/RpmhDxe/RpmhDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/RpmhDxe/RpmhDxe.efi
    SECTION UI = "RpmhDxe"
  }

  FILE DRIVER = 4b4973ee-401b-4f36-a6a9-533dfccdfc33 {
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ScmDxeLA/ScmDxeLA.efi
    SECTION UI = "ScmDxeLA"
  }

  FILE DRIVER = 8430c46d-ab1c-4f82-896b-33e156931fb3 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/ShmBridgeDxeLA/ShmBridgeDxeLA.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ShmBridgeDxeLA/ShmBridgeDxeLA.efi
    SECTION UI = "ShmBridgeDxeLA"
  }

  FILE DRIVER = f541d663-4a48-40aa-aabf-ff158ccae34c {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/SmemDxe/SmemDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/SmemDxe/SmemDxe.efi
    SECTION UI = "SmemDxe"
  }

  FILE DRIVER = 2a7b4bef-80cd-49e1-b473-374ba4d673fc {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/SPMI/SPMI.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/SPMI/SPMI.efi
    SECTION UI = "SPMI"
  }

  FILE DRIVER = cf6dfc66-14ab-4e13-84db-9c02912d1404 {
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/TzDxeLA/TzDxeLA.efi
    SECTION UI = "TzDxeLA"
  }

  FILE DRIVER = 0d35cd8e-97ea-4f9a-96af-0f0d89f76567 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/UFSDxe/UFSDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UFSDxe/UFSDxe.efi
    SECTION UI = "UFSDxe"
  }

  FILE DRIVER = E43128A8-8692-42B6-8AFA-676158578D18 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/ULogDxe/ULogDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/ULogDxe/ULogDxe.efi
    SECTION UI = "ULogDxe"
  }

  FILE DRIVER = 8bd3b475-401a-4b0b-9315-edee61a1eae5 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/VcsDxe/VcsDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/VcsDxe/VcsDxe.efi
    SECTION UI = "VcsDxe"
  }

  # FILE DRIVER = beb12bee-f6e1-11e1-9fb8-6c626de4aeb1 {
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/XhciPciEmulation/XhciPciEmulation.efi
  #   SECTION UI = "XhciPciEmulation"
  # }

  # FILE DRIVER = b7f50e91-a759-412c-ade4-dcd03e7f7c28 {
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/XhciDxe/XhciDxe.efi
  #   SECTION UI = "XhciDxe"
  # }

  # FILE DRIVER = 11faed4c-b21f-4d88-8e48-c4c28a1e50df {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/UsbPwrCtrlDxe/UsbPwrCtrlDxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UsbPwrCtrlDxe/UsbPwrCtrlDxe.efi
  #   SECTION UI = "UsbPwrCtrlDxe"
  # }

  # FILE DRIVER = 94f8a6a7-dc34-4101-88c1-99179cceae83 {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/UsbfnDwc3Dxe/UsbfnDwc3Dxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UsbfnDwc3Dxe/UsbfnDwc3Dxe.efi
  #   SECTION UI = "UsbfnDwc3Dxe"
  # }

  # FILE DRIVER = 2d2e62cf-9ecf-43b7-8219-94e7fc713dfe {
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UsbKbDxe/UsbKbDxe.efi
  #   SECTION UI = "UsbKbDxe"
  # }

  # FILE DRIVER = cd823a4d-7dec-4531-ae5d-4134fa4127b8 {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/UsbConfigDxe/UsbConfigDxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UsbConfigDxe/UsbConfigDxe.efi
  #   SECTION UI = "UsbConfigDxe"
  # }

  # FILE DRIVER = 0A134F0E-075E-40B3-9C63-3B3906804663 {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/UsbInitDxe/UsbInitDxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UsbInitDxe/UsbInitDxe.efi
  #   SECTION UI = "UsbInitDxe"
  # }

  # FILE DRIVER = 3299a266-15f0-4346-8318-716336736d3e {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/UsbDeviceDxe/UsbDeviceDxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UsbDeviceDxe/UsbDeviceDxe.efi
  #   SECTION UI = "UsbDeviceDxe"
  # }

  #   FILE DRIVER = 5AF77F10-90DF-4E7E-8325-A17EC09D5443 {
  #   SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm8350/UsbMsdDxe/UsbMsdDxe.depex
  #   SECTION PE32 = Platform/EFI_Binaries/Drivers/sm8350/UsbMsdDxe/UsbMsdDxe.efi
  #   SECTION UI = "UsbMsdDxe"
  # }
