  INF  Platform/EFI_Binaries/Drivers/sm6375/TzDxe/ScmDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/TzDxe/TzDxeLA.inf

  INF  Platform/EFI_Binaries/Drivers/sm6375/FontDxe/FontDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/QcomWDogDxe/QcomWDogDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6375/ChipInfoDxe/ChipInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/GLinkDxe/GLinkDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/SmemDxe/SmemDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/ULogDxe/ULogDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/NpaDxe/NpaDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6375/DALSYSDxe/DALSYSDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/VcsDxe/VcsDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/ClockDxe/ClockDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6375/HALIOMMUDxe/HALIOMMUDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/HWIODxe/HWIODxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/GpiDxe/GpiDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/I2CDxe/I2CDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/SPMIDxe/SPMIDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/SdccDxe/SdccDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/UFSDxe/UFSDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/TLMMDxe/TLMMDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6375/PlatformInfoDxe/PlatformInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/PmicDxe/PmicDxeLa.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/ChargerExDxe/ChargerExDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/QcomChargerDxe/QcomChargerDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/AdcDxe/AdcDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/TsensDxe/TsensDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/DDRInfoDxe/DDRInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6375/UsbMsdDxe/UsbMsdDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/UsbDeviceDxe/UsbDeviceDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/UsbConfigDxe/UsbConfigDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6375/PILDxe/PILDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/ShmBridgeDxe/ShmBridgeDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6375/ResetRuntimeDxe/ResetRuntimeDxe.inf